class XTP_EXCHANGE_TYPE:
    XTP_EXCHANGE_SH = 1
    XTP_EXCHANGE_SZ = 2
    XTP_EXCHANGE_UNKNOWN = 3


class XTP_MARKET_TYPE:
    XTP_MKT_INIT = 0
    XTP_MKT_SZ_A = 1
    XTP_MKT_SH_A = 2
    XTP_MKT_UNKNOWN = 3


class XTP_LOG_LEVEL:
    XTP_LOG_LEVEL_FATAL = 0
    XTP_LOG_LEVEL_ERROR = 1
    XTP_LOG_LEVEL_WARNING = 2
    XTP_LOG_LEVEL_INFO = 3
    XTP_LOG_LEVEL_DEBUG = 4
    XTP_LOG_LEVEL_TRACE = 5


class XTP_PROTOCOL_TYPE:
    XTP_PROTOCOL_TCP = 1
    XTP_PROTOCOL_UDP = 2


class XTP_PRICE_TYPE:
    XTP_PRICE_LIMIT = 1
    XTP_PRICE_BEST_OR_CANCEL = 2
    XTP_PRICE_BEST5_OR_LIMIT = 3
    XTP_PRICE_BEST5_OR_CANCEL = 4
    XTP_PRICE_ALL_OR_CANCEL = 5
    XTP_PRICE_FORWARD_BEST = 6
    XTP_PRICE_REVERSE_BEST_LIMIT = 7
    XTP_PRICE_LIMIT_OR_CANCEL = 8
    XTP_PRICE_TYPE_UNKNOWN = 9


